# Generated by Django 3.0.7 on 2021-03-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_remove_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislikes',
            new_name='retweet',
        ),
    ]
